### Target Guided Ordinal Encoding

It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In target guided Ordinal encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. this creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [1]:
import pandas as pd
df=pd.DataFrame({
    'city': ['new york', 'London', 'Paris', 'Tokyo', 'new york', 'Paris'],
    'price': [200, 150,300,250,180,320]
})

In [2]:
df

       city  price
0  new york    200
1    London    150
2     Paris    300
3     Tokyo    250
4  new york    180
5     Paris    320

In [4]:
mean_price= df.groupby('city')['price'].mean().to_dict()

In [5]:
mean_price

{'London': 150.0, 'Paris': 310.0, 'Tokyo': 250.0, 'new york': 190.0}

In [6]:
df['city_encoded'] = df['city'].map(mean_price)

In [7]:
df

       city  price  city_encoded
0  new york    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  new york    180         190.0
5     Paris    320         310.0

In [9]:
df[['city','city_encoded', 'price']]

       city  city_encoded  price
0  new york         190.0    200
1    London         150.0    150
2     Paris         310.0    300
3     Tokyo         250.0    250
4  new york         190.0    180
5     Paris         310.0    320

In [10]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Assignment: apply all Data Encoding Technique to the TIPS dataset