#### Data Manipulation and Analysis with Pandas
Data Manipulation and Analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform and extract insights from data. In this lesson, we will cover various manipulation and analysis techniques using Pandas

In [2]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

#fetch the first 5 rows
df.head(5)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [3]:
df.tail(5)

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [6]:
print(df.describe())
df.dtypes

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [8]:
### handling missing value
df.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
164    False
165    False
166    False
167    False
168    False
Length: 169, dtype: bool

In [9]:
df.isnull().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [10]:
df.fillna(0)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [12]:
## filling missing values with the mean of the column
df['Calories_fill']=df['Calories'].fillna(df['Calories'].mean())
df

     Duration  Pulse  Maxpulse  Calories  Calories_fill
0          60    110       130     409.1          409.1
1          60    117       145     479.0          479.0
2          60    103       135     340.0          340.0
3          45    109       175     282.4          282.4
4          45    117       148     406.0          406.0
..        ...    ...       ...       ...            ...
164        60    105       140     290.8          290.8
165        60    110       145     300.0          300.0
166        60    115       145     310.2          310.2
167        75    120       150     320.4          320.4
168        75    125       150     330.4          330.4

[169 rows x 5 columns]

In [14]:
df.dtypes

Duration           int64
Pulse              int64
Maxpulse           int64
Calories         float64
Calories_fill    float64
dtype: object

In [15]:
##rename column
df = df.rename(columns={'Duration': 'Time'})
df.head(5)

   Time  Pulse  Maxpulse  Calories  Calories_fill
0    60    110       130     409.1          409.1
1    60    117       145     479.0          479.0
2    60    103       135     340.0          340.0
3    45    109       175     282.4          282.4
4    45    117       148     406.0          406.0

In [22]:
## change datatype
df['Pulse_new'] = df['Pulse'].astype(int)
df.head(5)

   Time  Pulse  Maxpulse  Calories  Calories_fill  Value_new  Pulse_new
0    60    110       130     409.1          409.1      110.0        110
1    60    117       145     479.0          479.0      117.0        117
2    60    103       135     340.0          340.0      103.0        103
3    45    109       175     282.4          282.4      109.0        109
4    45    117       148     406.0          406.0      117.0        117

In [23]:
df['New_Maxpulse'] = df['Maxpulse'].apply(lambda x:x**2)
df.head(5)

,Time,Pulse,Maxpulse,Calories,Calories_fill,Value_new,Pulse_new,New_Maxpulse
0,60,110,130,409.1,409.1,110.0,110,16900
1,60,117,145,479.0,479.0,117.0,117,21025
2,60,103,135,340.0,340.0,103.0,103,18225
3,45,109,175,282.4,282.4,109.0,109,30625
4,45,117,148,406.0,406.0,117.0,117,21904

In [ ]:
##data aggregating and grouping
grouped_mean = df.groupby('Time')['Pulse'].mean()
print(grouped_mean)

In [25]:
grouped_sum = df.groupby(['Time', 'Pulse']) ['Calories'].sum()
print(grouped_sum)

Time  Pulse
15    80         50.5
      124       124.2
20    83         50.3
      95         77.7
      106       110.4
                ...
180   101       600.1
210   108      1376.0
      137      1860.4
270   100      1729.0
300   108      1500.2
Name: Calories, Length: 94, dtype: float64

In [26]:
grouped_agg = df.groupby('Time')['Pulse'].agg(['mean','sum','count'])
print(grouped_agg)

            mean   sum  count
Time
15    102.000000   204      2
20    125.000000  1125      9
25    152.000000   152      1
30    109.812500  1757     16
45    107.485714  3762     35
60    106.126582  8384     79
75    122.500000   245      2
80    123.000000   123      1
90     93.750000   750      8
120   100.000000   300      3
150   101.500000   406      4
160   109.500000   219      2
180    93.666667   281      3
210   122.500000   245      2
270   100.000000   100      1
300   108.000000   108      1

In [6]:
## merging and joining dataframes
#create sample data frame

df1 = pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','F'], 'Values2':[4,5,6]})
print(df1)
print(df2)

  Key  Value1
0   A       1
1   B       2
2   C       3
  Key  Values2
0   A        4
1   B        5
2   F        6

In [8]:
#merge dataframe on the key columns
pd.merge(df1,df2, on='Key', how = 'outer')

  Key  Value1  Values2
0   A     1.0      4.0
1   B     2.0      5.0
2   C     3.0      NaN
3   F     NaN      6.0

In [9]:
pd.merge(df1,df2, on='Key', how = 'inner')

  Key  Value1  Values2
0   A       1        4
1   B       2        5

In [10]:
pd.merge(df1,df2, on='Key', how = 'left')

  Key  Value1  Values2
0   A       1      4.0
1   B       2      5.0
2   C       3      NaN

In [11]:
pd.merge(df1,df2, on='Key', how = 'right')

  Key  Value1  Values2
0   A     1.0        4
1   B     2.0        5
2   F     NaN        6