In [1]:
import pandas as pd

In [3]:
#series
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
##create a series from dict element
data = {'a':1, 'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index=['a','b','c']
pd.Series(data,index = index)

a    10
b    20
c    30
dtype: int64

In [8]:
###dataframe
#create a dataframe from a dict of list


data ={
    'Name': ["krish", 'john', 'jack'],
    "Age": [25,22,24],
    'City': ['Dhaka', 'Rajshahi', 'Khulna']
    }
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  krish   25     Dhaka
1   john   22  Rajshahi
2   jack   24    Khulna
<class 'pandas.core.frame.DataFrame'>

In [5]:
import pandas as pd
df = pd.read_csv("sales.csv")
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [6]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [11]:
##accessing data from dataframe
df['Name']

0    krish
1     john
2     jack
Name: Name, dtype: object

In [12]:
df.loc[0]

Name    krish
Age        25
City    Dhaka
Name: 0, dtype: object

In [14]:
df.iloc[2]

Name      jack
Age         24
City    Khulna
Name: 2, dtype: object

In [15]:
df

    Name  Age      City
0  krish   25     Dhaka
1   john   22  Rajshahi
2   jack   24    Khulna

In [16]:
df.at[2,'Age']

np.int64(24)

In [17]:
df.at[2,'Name']

'jack'

In [18]:
df.iat[2,2]

'Khulna'

In [19]:
df

    Name  Age      City
0  krish   25     Dhaka
1   john   22  Rajshahi
2   jack   24    Khulna

In [21]:
#data manipulation with dataframe
# add column
df['Salary']=[4000,5000,6000]
df

    Name  Age      City  Salary
0  krish   25     Dhaka    4000
1   john   22  Rajshahi    5000
2   jack   24    Khulna    6000

In [25]:
#remove a column
df.drop('Age', axis= 1,inplace=True)

KeyError: "['Age'] not found in axis"

In [26]:
df

    Name      City  Salary
0  krish     Dhaka    4000
1   john  Rajshahi    5000
2   jack    Khulna    6000

In [27]:
df = pd.read_csv('sales.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
#display the data types of each column
print("Data types:\n",df.dtypes)

#describe the dataframe
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

KeyError: 'Category'